name: Release
on: workflow_dispatch
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
        with:
          fetch-depth: 0
          token: ${{ secrets.COSIUM_JENKINS_GITHUB_PUBLIC_REPO_PAT }}
      - name: Setup environment
        uses: actions/setup-java@v3
        with:
          java-version: '17'
          distribution: 'adopt'
          server-id: ossrh
          server-username: MAVEN_USERNAME
          server-password: MAVEN_PASSWORD
      - name: Install GPG private key
        run: |
          cat <(echo -e "${{ secrets.COSIUM_JENKINS_GPG_PRIVATE_KEY }}") | gpg --batch --import
          gpg --list-secret-keys --keyid-format LONG
      - name: Release
        run: |
          git config user.name cosium-jenkins
          git config user.email jenkinsbot@cosium.com
          ./release.sh
        env:
          MAVEN_USERNAME: ${{ secrets.COM_COSIUM_MAVEN_USERNAME }}
          MAVEN_PASSWORD: ${{ secrets.COM_COSIUM_MAVEN_TOKEN }}
