name: Release
on: workflow_dispatch
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - name: Setup environment
        uses: actions/setup-java@v3
        with:
          java-version: '17'
          distribution: 'adopt'
          server-id: ossrh
          server-username: MAVEN_USERNAME
          server-password: MAVEN_PASSWORD
      - name: Release
        run: ./release.sh
        env:
          MAVEN_USERNAME: ${{ secrets.COM_COSIUM_MAVEN_USERNAME }}
          MAVEN_PASSWORD: ${{ secrets.COM_COSIUM_MAVEN_TOKEN }}
